# Generated by Django 4.1.7 on 2023-03-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_created', models.TimeField(auto_created=True)),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_salary', models.IntegerField(max_length=200)),
                ('employee_address', models.TextField(max_length=200)),
            ],
        ),
    ]
