# Generated by Django 4.1.7 on 2023-03-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_salary',
            field=models.IntegerField(),
        ),
    ]
